# Generated by Django 2.2 on 2020-01-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=512)),
                ('domain', models.CharField(max_length=2048)),
                ('auth_token', models.CharField(max_length=512)),
                ('api_app_id', models.CharField(max_length=512)),
                ('default_channel', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('channel', models.CharField(max_length=1024)),
                ('is_complete', models.BooleanField(default=False)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slack.Slack')),
            ],
        ),
    ]
