# Generated by Django 2.2 on 2020-01-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Connector', '0003_sscconnector_user_id'),
        ('Slack', '0002_slack_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slack',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='slack',
            name='domain',
        ),
        migrations.AddField(
            model_name='slack',
            name='source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Connector.SSCConnector'),
        ),
    ]
