# Generated by Django 2.2 on 2020-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_url', models.URLField(max_length=255)),
                ('email_id', models.EmailField(max_length=200)),
                ('api_key', models.TextField()),
                ('project_key', models.TextField()),
            ],
        ),
    ]
