# Generated by Django 2.2 on 2020-01-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira',
            name='app_url',
            field=models.TextField(),
        ),
    ]
