# Generated by Django 2.2 on 2020-01-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0002_auto_20200106_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira',
            name='app_url',
            field=models.URLField(),
        ),
    ]
