# Generated by Django 2.2 on 2020-01-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0003_auto_20200107_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira',
            name='jira_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jira',
            name='email_id',
            field=models.TextField(),
        ),
    ]
