# Generated by Django 2.2 on 2020-01-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jira', '0006_jira_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jira',
            name='user_id',
        ),
    ]
