# Generated by Django 2.2 on 2020-01-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sscconnector',
            name='user_id',
        ),
    ]
