# Generated by Django 2.2 on 2020-01-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Connector', '0002_remove_sscconnector_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscconnector',
            name='user_id',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
